//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHSchool.Retake.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SHSchool.Retake.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap barchart_64 {
            get {
                object obj = ResourceManager.GetObject("barchart_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap brand_write_64 {
            get {
                object obj = ResourceManager.GetObject("brand_write_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap desk_64 {
            get {
                object obj = ResourceManager.GetObject("desk_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Import_Image {
            get {
                object obj = ResourceManager.GetObject("Import_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap lesson_planning_clock_64 {
            get {
                object obj = ResourceManager.GetObject("lesson_planning_clock_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap marker_fav_64 {
            get {
                object obj = ResourceManager.GetObject("marker_fav_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap Report {
            get {
                object obj = ResourceManager.GetObject("Report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;重補修課程資料&quot;&gt;
        ///    &lt;DuplicateDetection&gt;
        ///        &lt;Detector Name=&quot;組合鍵值&quot;&gt;
        ///            &lt;Field Name=&quot;課程名稱&quot; /&gt;
        ///            &lt;Field Name=&quot;學年度&quot; /&gt;
        ///            &lt;Field Name=&quot;學期&quot; /&gt;
        ///            &lt;Field Name=&quot;梯次&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///    &lt;/DuplicateDetection&gt;
        ///    &lt;FieldList&gt;
        ///
        ///        &lt;Field Required=&quot;True&quot; Name=&quot;課程名稱&quot; Description=&quot;課程名稱&quot;&gt;
        ///            &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「課程名稱」 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string RetakeCourse {
            get {
                return ResourceManager.GetString("RetakeCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;重補修學生修課&quot;&gt;
        ///    &lt;DuplicateDetection&gt;
        ///        &lt;Detector Name=&quot;組合鍵值&quot;&gt;
        ///            &lt;Field Name=&quot;課程名稱&quot; /&gt;
        ///            &lt;Field Name=&quot;學年度&quot; /&gt;
        ///            &lt;Field Name=&quot;學期&quot; /&gt;
        ///            &lt;Field Name=&quot;梯次&quot; /&gt;
        ///	    &lt;Field Name=&quot;學號&quot; /&gt;
        ///        &lt;/Detector&gt;
        ///    &lt;/DuplicateDetection&gt;
        ///    &lt;FieldList&gt;
        ///
        ///
        ///  &lt;Field Required=&quot;True&quot; Name=&quot;課程名稱&quot; Description=&quot;課程名稱&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Des [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string RetakeSCAttend {
            get {
                return ResourceManager.GetString("RetakeSCAttend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap subject_del {
            get {
                object obj = ResourceManager.GetObject("subject_del", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;重補修科目管理&quot;&gt;
        ///  &lt;DuplicateDetection&gt;
        ///    &lt;Detector Name=&quot;組合鍵值&quot;&gt;
        ///      &lt;Field Name=&quot;科目名稱&quot; /&gt;
        ///      &lt;Field Name=&quot;級別&quot; /&gt;
        ///      &lt;Field Name=&quot;學分數&quot; /&gt;
        ///      &lt;Field Name=&quot;所屬課表&quot; /&gt;
        ///    &lt;/Detector&gt;
        ///  &lt;/DuplicateDetection&gt;
        ///  &lt;FieldList&gt;
        ///
        ///    &lt;Field Required=&quot;True&quot; Name=&quot;科目名稱&quot; Description=&quot;科目名稱&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「科目名稱」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; Whe [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string SubjectList {
            get {
                return ResourceManager.GetString("SubjectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap time_frame_refresh_128 {
            get {
                object obj = ResourceManager.GetObject("time_frame_refresh_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 刪除課程 {
            get {
                object obj = ResourceManager.GetObject("刪除課程", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 匯出 {
            get {
                object obj = ResourceManager.GetObject("匯出", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 匯出修課學生 {
            get {
                object obj = ResourceManager.GetObject("匯出修課學生", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 及格人數樣板 {
            get {
                object obj = ResourceManager.GetObject("及格人數樣板", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 學生選課清單 {
            get {
                object obj = ResourceManager.GetObject("學生選課清單", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 學生重補修缺曠通知單扣考範本 {
            get {
                object obj = ResourceManager.GetObject("學生重補修缺曠通知單扣考範本", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 學生重補修缺曠通知單範本 {
            get {
                object obj = ResourceManager.GetObject("學生重補修缺曠通知單範本", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 建議重補修名單_filter_data_add_64 {
            get {
                object obj = ResourceManager.GetObject("建議重補修名單_filter_data_add_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 新增課程 {
            get {
                object obj = ResourceManager.GetObject("新增課程", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 缺曠通知單學生名單範本 {
            get {
                object obj = ResourceManager.GetObject("缺曠通知單學生名單範本", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 缺曠通知單範本 {
            get {
                object obj = ResourceManager.GetObject("缺曠通知單範本", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 課程基本資料 {
            get {
                object obj = ResourceManager.GetObject("課程基本資料", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 課程缺曠名單樣板 {
            get {
                object obj = ResourceManager.GetObject("課程缺曠名單樣板", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 課程點名單樣板 {
            get {
                object obj = ResourceManager.GetObject("課程點名單樣板", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 重補修科目管理_project_64 {
            get {
                object obj = ResourceManager.GetObject("重補修科目管理_project_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] 重補修課程缺曠樣板 {
            get {
                object obj = ResourceManager.GetObject("重補修課程缺曠樣板", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 重補修課表管理_schedule_write_64 {
            get {
                object obj = ResourceManager.GetObject("重補修課表管理_schedule_write_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap 開課 {
            get {
                object obj = ResourceManager.GetObject("開課", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
